### ISSUE TITLE
[Enhancement] add multiple class to body and/or wrapper

### ISSUE THREAD

**Issue by namnn** [KevCJones/ngx-simple-modal#23]
I just want to propose an enhancement.

Instead of adding/removing directly wrapperClass or bodyClass to/from the element list, it would be nice if you can split them to string[] prior to mutating the classList. Currently it's kind of limited to one string only.

**Comment by KevCJones** [comment]
Could you explain a little bit more for me? Perhaps describe a simple use-case?

**Comment by namnn** [comment]
It's really up to you, but I think it would be more flexible if developers can add "a b c" rather than just "a" to wrapperClass or bodyClass.

In my opinion, apps with existing styles can switch to this library with more flexibility. Anyway, this is just a little thing.
