### ISSUE TITLE
Strange behavior when interacting with ng-select module

### ISSUE THREAD

**Issue by pikachumetal** [KevCJones/ngx-simple-modal#25]
Hi,

I was trying to migrate from ng2-bootstrap-modal, and i found and strange interaction with the module ng-select (https://github.com/basvandenberg/ng-select).

When i open and select from the dropdown (ng-select) in a modal, the dropdown did not close.
When the ng-select is not in a modal work properlly.

Here you can test this issue:
https://stackblitz.com/edit/angular-tldpgy

Note that, when we use ng2-bootstrap-modal, this not happen.

Thanks in advance

**Comment by KevCJones** [comment]
I will look for you today. I suspect click was captured and ng-modal is
after it on body

**Comment by KevCJones** [comment]
@pikachumetal pikachumetal, as i suspected its to do with our default behaviour to close an alert using the `closeOnClickOutside` config. One immediate thing you can do to remedy this is to turn that feature off. See [https://angular-vbpjd6.stackblitz.io](https://angular-vbpjd6.stackblitz.io) for working  behaviour .

```
this.SimpleModalService.addModal(AlertComponent, {title: 'Alert title!', message: 'Alert message!!!'}, { closeOnClickOutside: false});
```

I will see if there is a way i can achieve both in the mean time

**Comment by KevCJones** [comment]
Here you go @pikachumetal  https://stackblitz.com/edit/ngx-simple-modal-with-ng-modal a working demo, you tipped me off to a wider issue which i documented in #26. By and large you should be able to do what you expected without issues now. Key notes

- install version 1.3.1
- be aware that `closeOnClickOutside` defaults to false again as was intended but both will work now
- i modded your demo to show how you can get the result via subscription, just for fun.
