### ISSUE TITLE
TypeScript error for SimpleModalComponent.onClosing

### ISSUE THREAD

**Issue by cubitworx** [KevCJones/ngx-simple-modal#27]
https://github.com/KevCJones/ngx-simple-modal/blob/1e29f0e18d8acb6a5c843250891ff61fa44da71f/src/simple-modal/simple-modal.component.ts#L80

When using this module in a typescript project (v2.6.2) the above method signature produces the following error:
```
ERROR in [at-loader] ./node_modules/ngx-simple-modal/dist/simple-modal/simple-modal.component.d.ts:13:26
TS7006: Parameter 'component' implicitly has an 'any' type.
```

I assume it should be typehinted as follows:
```
onClosing(callback: (component: SimpleModalComponent<any, any>) => Promise<any>): void {
```

This could be overcome by using [skiplibcheck: true](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#new---skiplibcheck) but not a good setting to impose on a user.

**Comment by KevCJones** [comment]
New TS version, new problems. Simple enough fix at least, thanks for finding.

**Comment by KevCJones** [comment]
Is not part of ngx-simple-modal@latest.
