### ISSUE TITLE
Optional config argument is not checked before being used

### ISSUE THREAD

**Issue by cubitworx** [KevCJones/ngx-simple-modal#28]
https://github.com/KevCJones/ngx-simple-modal/blob/1e29f0e18d8acb6a5c843250891ff61fa44da71f/src/simple-modal/simple-modal.service.ts#L39-L40

Config is optional & yet is used without being checked. This forces you to always need to call `forRoot` when adding the module to a project.

**Comment by KevCJones** [comment]
Yes thats i think i've always used the config so its slipped by, i will write a test to catch this as well but for now the PR resolves.

**Comment by KevCJones** [comment]
ngx-simple-modal@latest now contains this fix and it works as expected.  Thanks again for the catch.
