### ISSUE TITLE
changing global default options

### ISSUE THREAD

**Issue by Tahiche** [KevCJones/ngx-simple-modal#32]
Hi,
I want to have some global options for all modals, for example "closeOnEscape: true,
  closeOnClickOutside: true,". Don´t want to specify that on every .addModal() call, it seems redundant.
I can´t see an obvious way to do this. 
These default options seem to be set in SimpleModalHolderComponent, so it looks like they can´t be overriden at extending component either.

```
....
import { defaultModalOptions, SimpleModalOptions } from './simple-modal-options';
....

// assign options refs
    _component.options = options = Object.assign({}, defaultModalOptions, options);
```

**Comment by KevCJones** [comment]
Seems like a reasonable request, i'll carve out some time.

My initial thinking is to make the defaultOptions an @injectable instead of a flat import and then it can be provided by you on a per module basis where ever you choose to import it.

```
{ provide: defaultSimpleModalOptions , useValue: <default here> }
```

Thoughts?

**Comment by Tahiche** [comment]
Injectable sounds like a good approach, I´m assuming you mean a ConfigService kind of thing that you can inject and thus override/modify.
If i´m not mistaken, here...
`{ provide: defaultSimpleModalOptions , useValue: <default here> }`
You´d be modifying/customizing default Options globally, at Module level?. That´s great, then you could further override if needed by injecting the service at specific components.

**Comment by KevCJones** [comment]
@Tahiche give that branch a look over. Feedback welcome.

**Comment by KevCJones** [comment]
I'm going to push this anyway @Tahiche  but your feedback on it would be welcome since you initiated the request

**Comment by Tahiche** [comment]
Hi!,
So sorry i missed these comments!. It looks great, thank u very much!!. I´ll check it out.
Again, sorry for not answering before I wasn´t noticed and totally missed it.

Cheers!!
