### ISSUE TITLE
Add 'modal' and 'fade' classes to configuration.

### ISSUE THREAD

**Issue by Aracturat** [KevCJones/ngx-simple-modal#35]
Is it possible to add the names of these classes (or maybe all template html) in component definition below to configuration?
```
@Component({
  selector: 'simple-modal-wrapper',
  template: '
    <div #wrapper class="modal fade" [ngStyle]="{display:'block'}" role="dialog">
        <ng-template #viewContainer></ng-template>
    </div>'
})

**Comment by KevCJones** [comment]
Hey @Aracturat could you outline for me a little more the problem you're trying to solve. I'm not 100% what you want to achieve  that it can't now? Much appreciated.

**Comment by Aracturat** [comment]
So, I have two different problems:
1. I want to use BEM notation and\or prefixes in my code.
So, for example I want to have `o-modal` instead of `modal`, `o-modal--fade` instead of `fade` .

2. Sometimes our modals contains two parts: the firt part is same for all, another is different. With ability to set template it is will be easier to maintaing such modals.

**Comment by KevCJones** [comment]
I see, so you're looking for overrides to the classes that are within the wrapper itself, I follow you now. No harm in.  I honestly thought i'd done this once, but maybe we dropped it for simplicity.

**Comment by KevCJones** [comment]
@Aracturat give the PR a review and let me know if i've understood your requirement.

**Comment by Aracturat** [comment]
@KevCJones Thank you! It is ok for me =)
