### ISSUE TITLE
Issue with Bootstrap 4

### ISSUE THREAD

**Issue by jcaudill** [KevCJones/ngx-simple-modal#41]
My project was previously using Bootstrap 3 which had no problems.  After changing the CSS reference to Bootstrap 4 -- no more worky.

I've also tried to get the demo from this repo working with Bootstrap 4 but it has the same problem.  The dialog flashes (not visible to the eye) and then the page is unresponsive.

Anyone successfully using this with Bootstrap 4.  I may have to change directions because I'm running short on time.

**Comment by KevCJones** [comment]
I away right now but I will look into it. The lib as a rule is fairly
agnostic of any visual implementation. That being said, it's likely I just
need to do a BS4 example and double check any of the base class choices
made are not causing issues.

Feel free to make a stackblitz example of your issue and post here if you
have time in the meantime.

**Comment by jcaudill** [comment]
@KevCJones here is the [stackblitz](https://stackblitz.com/edit/angular-modal-dialog-issue).

It is currently in the broken state using bootstrap 4.  If you change the bootstrap reference in the index.html to the bootstrap 3 link it works.  With the bootstrap 4 link it does not.  If you also comment out all bootstrap links and add the ngx-simple-modal css to the angular.json styles it works.

I have to get the problem solved pretty quickly or I'm going to have to find a new solution.  I prefer this component over all others I've tried so it would be great if you could help me figure this out.

**Comment by jcaudill** [comment]
I’ve found that this issue appears to be related to the use of the fade style.  I’ll post specifics tomorrow.

**Comment by KevCJones** [comment]
Sorry, I've been neck deep in project work. Is it something you can fix by
changing the class for wrapper in config?

**Comment by jcaudill** [comment]
@KevCJones Yes all it took was the removal of 'fade' from the 'wrapperDefaultClasses'
Perhaps eventually we can dig in and find why this doesn't work with bootstrap 4 but does with bootstrap 3.  Until then, this provides ample workaround for my project.  Thanks.

**Comment by KevCJones** [comment]
fixed in ngx-simple-modal@1.3.12 - fade class renamed to fade-anim to avoid conflict
