### ISSUE TITLE
ngOnDestroy

### ISSUE THREAD

**Issue by Grayfox12** [KevCJones/ngx-simple-modal#45]
Can you add to docs about ngOnDestroy override? Cause if i implement ngOnDestroy method in my modal component, observable.next not working. And listener doesnt know about event from modal window

**Comment by KevCJones** [comment]
I'll check that, I seem to remember their being a good reason for doing
stuff in destroy. When get back to a screen I'll review. Event listeners on
document rings a bell and making sure I clean up , even when the app
destroys the modal not the user.

**Comment by Grayfox12** [comment]
oh yes. And if i override ngondestroy, i have memory leak with unsubscrible observable)))

**Comment by KevCJones** [comment]
fixed in 1.3.10
