### ISSUE TITLE
Property 'onKeydownHandler' is private and only accessible within class 'SimpleModalComponent<T, T1>'.

### ISSUE THREAD

**Issue by freon27** [KevCJones/ngx-simple-modal#47]
Hi,

It seems that the handler function is defined as private which means it's not accessible from within the template. This isn't an issue when doing a CLI build but generates an error when trying to use ng-packagr under Angular 6 (worked ok in angular 5).

**Comment by KevCJones** [comment]
Ah , thanks Im kinda locked down for the moment in 5 land right now. Is
this as easy as making it public then?

**Comment by freon27** [comment]
Yep, it appears so....

We manually hacked the definitions file to remove the private modifier and
that was enough to make it work. It makes sense that it needs to be public
anyway since it's called from outside the class.

**Comment by KevCJones** [comment]
i'm willing to make this public its not a big thing but its not something intended to be called from outside originally. The @HostListener decorator was more about automatically handling based on the config you set. 

```
  @HostListener('document:keydown.escape', ['$event'])
  onKeydownHandler(evt: KeyboardEvent) {
    if (this.options && this.options.closeOnEscape) {
      this.close();
    }
  }
```

I don't suppose you'd be happy to share your ng-packagr so i could try and replicate here? Not used it before it would be helped me along too.

K

**Comment by freon27** [comment]
This is all that's in the ng-packagr.json:

`{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts",
    "styleIncludePaths": ["src/styles.scss"]
  },
  "whitelistedNonPeerDependencies": ["."]
}
`

**Comment by KevCJones** [comment]
Thanks, if you hadn't noticed I released a new version which means you can
remove your patched copy

**Comment by freon27** [comment]
Cool, thanks!
