### ISSUE TITLE
How to dispose instance of modal

### ISSUE THREAD

**Issue by Navyasri-Gurram** [KevCJones/ngx-simple-modal#48]
I have opened a modal and and closed it back but instance is remaining and i have add few shortcut keys to raise in that model after closing my modal all the tie my call goes to that instance

  async showMessagePopup(message, isAlert, isConfirmation, isInformation) {

    var isConfirmed = await this.simpleModalService.addModal(AlertFrameworkComponent, {

      popupTitle: 'Hello',
      message: message,
      isAlert: isAlert,
      isConfirmation: isConfirmation,
      isInformation: isInformation
    }).toPromise();

    return isConfirmed;
  }

this.simpleModalService.removeAll();

modal component logic
KeyboardEventRaised = (event: KeyboardEvent, key: string): boolean => {

    console.log(document.activeElement.id);

    if (document.activeElement.id == 'YesClick' || document.activeElement.id == 'NoClick') {

      event.preventDefault();

      this.RaiseKeyDownEvent(key);
    }

    return true;
  }

**Comment by KevCJones** [comment]
Hey, I'm trying to fully understand, is it possible to make a stack blitz
to demo the issue

K

**Comment by KevCJones** [comment]
Any update on the above would be useful, appreciate the code snippets but a demo is always better for me to edit and send back a fix if i can or add a fix to the codebase if i cannot.
