### ISSUE TITLE
Metadata version missmatch. Found version 4, expected 3

### ISSUE THREAD

**Issue by FelixSalyr** [KevCJones/ngx-simple-modal#51]
Whenever I add a new module to my project I get a compiler error stating that this dependency has a metadata version mismatch (I think it's complaining about my Angular version). I have Angular v 4 and it expects Angular v 3. I looked through the npm page for the package and it seems to say that it should work with any version of Angular 2+. In the past I have resolved this by deleting my node_modules folder and doing a fresh install. This time, however, it seems to not be working. 

Using angular 4.2.4 
Using ngx-simple-modal 1.3.12

Any tips or guidance would be greatly appreciated.

**Comment by KevCJones** [comment]
is this still an issue? Can't say i've seen this myself and i use it in production now on ng7 and soon to be ng8

**Comment by KevCJones** [comment]
Now using this on an angular8 project.  Closing unless i get another report.
