### ISSUE TITLE
Can we remove this console.log?

### ISSUE THREAD

**Issue by kameelyan** [KevCJones/ngx-simple-modal#55]
https://github.com/KevCJones/ngx-simple-modal/blob/5c91e25da94eb1a3cf74fa280a282d40318eaefe/src/simple-modal/simple-modal-wrapper.component.ts#L65

Can we remove this console.log please?

**Comment by KevCJones** [comment]
Yeah, if you can make a PR to master, I'll appreciate it. I can do a
release later on

**Comment by kameelyan** [comment]
https://github.com/KevCJones/ngx-simple-modal/pull/56

**Comment by KevCJones** [comment]
Ta will bump  version today

**Comment by KevCJones** [comment]
Release 1.3.24
