### ISSUE TITLE
Replace bootstrap css with local css 

### ISSUE THREAD

**Issue by KevCJones** [KevCJones/ngx-simple-modal#6]
- [x] Create a simple-modal.css file for the component
- [x] Import into demo project
- [x] Remove bootstrap from demo
- [x] Update readme to show how CSS works and explain that they can also use bootstrap or other frameworks if they want to.

**Comment by KevCJones** [comment]
How goes this side of things for you? I've got a planned update of the packaging to npm steps to stop #12 error on AOT builds

**Comment by celsomtrindade** [comment]
@KevCJones I was locked into a client project. But did it now, hope it's how you expected it to be.

> Note: I didn't had much time to test. If you can, please, check if it's everything ok.

**Comment by KevCJones** [comment]
Took your PR - into same name one in the end. Then did some minor adjustments. If you're ok with it, i'll merge in and close this
