### ISSUE TITLE
Hide Modal visibility on page redirect

### ISSUE THREAD

**Issue by Navyasri-K** [KevCJones/ngx-simple-modal#60]
I am using Angular 4 to build my application. When i redirect to another url that is from one component to another component if my modal popup is opened then it should not be visible in redirected component. 
Let suppose i have 2 components
HelloWorkldComponent
ByeComponent

In HelloWorkldComponent i have raised a modal with enabling the background.
Now from routing am trying to redirect to my ByeComponent, then my modal popup is visible in ByeComponent component as well, but i need modal popup not to be visible in ByeComponent. How can i resolve this. Please help me.

Thanks in advance.

**Comment by KevCJones** [comment]
Hi, could you replicate this on stackblitz for me?

**Comment by KevCJones** [comment]
Closing issue but willing to open if a demonstration is provided.
