### ISSUE TITLE
AutoFocus doesn't trigger if animationDuration is 0

### ISSUE THREAD

**Issue by KilleR** [KevCJones/ngx-simple-modal#64]
See title:

I you configure autoFocus: true, and animationDuration: 0, the autoFocus will not be triggered.

**Comment by KevCJones** [comment]
Interesting, I'll look into that thanks :neutral_face: meanwhile, use a small number instead of zero.

**Comment by KevCJones** [comment]
@KilleR could you spin up a stackBlitz for this to demonstrate? I couldn't replicate.

**Comment by KevCJones** [comment]
For now my advice is don't do that. I'll look at it when i can though and leave this open in the meantime
