### ISSUE TITLE
Dynamic modal classes

### ISSUE THREAD

**Issue by doup** [KevCJones/ngx-simple-modal#65]
Hi, I'm trying to reproduce iOS style stacked modals, I've been able to do a decent job just with CSS, but there are few issues that bother me:

![tg-modal-stack-on](https://user-images.githubusercontent.com/188612/72618418-50392f00-393b-11ea-8c37-3e0419b4846a.gif)

- ☝️ I'm relying on CSS `simple-modal-wrapper:nth-last-child(n)` to modify the size/position of the modals. `nth-last-child` rule that depends on the existence of sibling elements, basically:
  - `...`
  - `simple-modal-wrapper:nth-last-child(3) { transform: scale(80%); }`
  - `simple-modal-wrapper:nth-last-child(2) { transform: scale(90%); }`
  - `simple-modal-wrapper:nth-last-child(1) { transform: scale(100%); }`

![tg-modals-stack-off](https://user-images.githubusercontent.com/188612/72618439-5d561e00-393b-11ea-9b85-54b65c7962f2.gif)

- ☝️When closing, it doesn't trigger the animation as the CSS hack is based on the presence of the `simple-modal-wrapper` element. So first it does the slide down & fade animation, then top-most modal is removed, only after that the other modals scale up. It's ugly.

![tg-modals-alert](https://user-images.githubusercontent.com/188612/72618516-87a7db80-393b-11ea-86fb-89ce12d15550.jpg)

- ☝️Finally, this won't work with the above explained CSS hack. I want to open a new modal (custom alert) above the already stacked modals, but I don't want the new modal to affect the stacking (scale) of the previously opened ones as it's a different kind of modal. It should just open hover.

I think all these issues could be solved if either `wrapperClass` or `bodyClass` from the options object accepted a function. This function would be executed at the moment a modal is instantiated.

It would receive the number of already opened modals (or an array containing the instances) & the instance/class/type of the modal that its being instantiated. Based on these parameter it would be feasible to decide what class the modal should have.

Thanks!

**Comment by doup** [comment]
I want to implement something to handle this scenario. What's the approach I should take so that you'll be confortable merging the feature?

What do you think on having a callback on the config which decides which class to apply? Or maybe it would be more like a life-cycle hook where the library-user can patch the newly created modal.

**Comment by KevCJones** [comment]
I liked your idea with a function that you could simply resolve it.
Simplest change for the moment is better.

Life cycle is a nice idea but probably I'd want more thinking time before
opening that door.

Sorry I've been pretty busy at work to sort this out. Appreciate all
contributions in advance.

**Comment by KevCJones** [comment]
By the way - just a note to say it's really cool to see something unique made with this. You've pushed it further than i ever have 👏 👏 👏

**Comment by KevCJones** [comment]
Did you manage to put a PR together for this?

**Comment by KevCJones** [comment]
Closing until you comeback with something or i pick it up myself.
