### ISSUE TITLE
mapDataObject doesn't check for null values resulting in a TypeError

### ISSUE THREAD

**Issue by sleziak** [KevCJones/ngx-simple-modal#68]
```  
mapDataObject(data: T): void {
    data = data || <T>{};
    const keys = Object.keys(data);
    for (let i = 0, length = keys.length; i < length; i++) {
      const key = keys[i];
      if (typeof data[key] === 'object' && typeof this[key] === 'object') {
        Object.assign(this[key], data[key]);
      } else {
        this[key] = data[key];
      }
    }
  }
```
`typeof NULL` is unfortunately an object in JavaScript. 
When a property inside the modal component defaults to NULL, then the Object.assign function throws an exception trying to assign a value to that null object.

`TypeError: "can't convert null to object"`

The condition should be changed to this or a similar check that checks for null values.
```(data[key] &&  this[key] && typeof data[key] === 'object' && typeof this[key] === 'object')```

The change happened in the following commit: https://github.com/KevCJones/ngx-simple-modal/commit/91f7f4b03dc4bad4f66fb11d5870a403ded41314

**Comment by KevCJones** [comment]
Thanks and a good shout - applied and is not in version 1.4.13. Sorry it took so long to get something so trivial merged in.
