### ISSUE TITLE
Component inside modal with @HostListener('document.click') doesn't work

### ISSUE THREAD

**Issue by yadue** [KevCJones/ngx-simple-modal#69]
If you have modal set, and inside that modal you put any component with @HostListener('document.click')
then the event is not being propagated. It's strictly related to stopPropagation inside SimpleModalWrapperComponent.

All angular events should work as expected.

**Comment by KevCJones** [comment]
Many thanks for contributing. 
Is now released - https://www.npmjs.com/package/ngx-simple-modal/v/1.4.12
