### ISSUE TITLE
Model does not trap focus

### ISSUE THREAD

**Issue by rmatherly** [KevCJones/ngx-simple-modal#72]
I have found that when a modal is open, I can tab out of the modal element and into other parts of the page and interact with elements using the keyboard.  I have fixed some of this by setting a working flag to disable buttons when the modal is open, but it is a bit cumbersome and not perfect... hyperlinks, for example, can still be triggered.  This make for a strange experience because the router changes the content behind the modal, but the modal stays open.  I haven't had a lot of time to dig into this yet, but was wondering if you were aware of this limitation and have any ideas of ways to work around it.  It would be great if there was a global setting to trap the focus to the modal-content element.  I know Bootstrap Modal has a way to do this, but I'm not sure how it works.  If I get a chance, I will research it further.

**Comment by KevCJones** [comment]
I've been using a11y module from Material with success for trapping. Perhaps i've not documented this well enough but you can use the ready$ observable exposed by the modal to give you a trigger of when to trap. 

```
<div class="c-modal__wrap" [cdkTrapFocus]="ready$ | async">
...
```

Try the above in one of your modals or whatever trapping mechanism you're attempting.

**Comment by KevCJones** [comment]
In short, I did not put trapping into the modal component itself, I left it up to you to decide which you use, I've just exposed the trigger of when the modal has finished rendering and is ready[$] to be trapped.

**Comment by rmatherly** [comment]
This worked great!  I didn't know there was a trap focus directive as part of the CDK, and it didn't come up in any of my searches for some reason.  Thank you for the quick response.

**Comment by rmatherly** [comment]
This worked great!  I didn't know there was a trap focus directive as part of the CDK, and it didn't come up in any of my searches for some reason.  Thank you for the quick response.

**Comment by rmatherly** [comment]
This worked great!  I didn't know there was a trap focus directive as part of the CDK, and it didn't come up in any of my searches for some reason.  Thank you for the quick response.

**Comment by rmatherly** [comment]
This worked great!  I didn't know there was a trap focus directive as part of the CDK, and it didn't come up in any of my searches for some reason.  Thank you for the quick response.

**Comment by rmatherly** [comment]
This worked great!  I didn't know there was a trap focus directive as part of the CDK, and it didn't come up in any of my searches for some reason.  Thank you for the quick response.

**Comment by rmatherly** [comment]
This worked great!  I didn't know there was a trap focus directive as part of the CDK, and it didn't come up in any of my searches for some reason.  Thank you for the quick response.

**Comment by rmatherly** [comment]
This worked great!  I didn't know there was a trap focus directive as part of the CDK, and it didn't come up in any of my searches for some reason.  Thank you for the quick response.

**Comment by KevCJones** [comment]
Good stuff, glad it's what you needed... and yeah the CDK has some really useful utils like this.
